### ISSUE TITLE
HowTO: simple http/https LB

### ISSUE THREAD

**Issue by linecolumn** [facebookincubator/katran#105]
Is there any sample/simple deployment step by step guide for http/https Layer4 Load Balancer with Katran?

**Comment by tehnerd** [comment]
EXAMPLE.md probably the most detailed one document for end user. The only difference for your usecase is that instead of port 22, dst port should be 443 and 80

**Comment by udippant** [comment]
@linecolumn Let us know if you have further questions after going over the tutorials in the Example.md (https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md).

**Comment by carnivorelogic** [comment]
@udippant was reading (very informative) https://github.com/facebookincubator/katran/issues/21 and it seems some of the lessons from this Issue can be implemented to more comprehensive EXAMPLE.md?

I'm interested in benefits of using only one NIC for incoming and forwarding to backend servers. Couldn't it be more "efficient" to receive on NIC which is facing to client then sending over other NIC to backand servers, which will accept it via one NIC and do Direct Response via client/public facing NIC?

**Comment by linecolumn** [comment]
@udippant was reading (very informative) #21 and it seems some of the lessons from this Issue can be implemented to more comprehensive EXAMPLE.md?

I'm interested in benefits of using only one NIC for incoming and forwarding to backend servers. Couldn't it be more "efficient" to receive on NIC which is facing to client then sending over other NIC to backand servers, which will accept it via one NIC and do Direct Response via client/public facing NIC?

**Comment by tehnerd** [comment]
>@udippant was reading (very informative) #21 and it seems some of the lessons from this Issue can be implemented to more > comprehensive EXAMPLE.md?

could FB folks chime in here, as an owner of this repo?

>
> I'm interested in benefits of using only one NIC for incoming and forwarding to backend servers. Couldn't it be more >"efficient" to receive on NIC which is facing to client then sending over other NIC to backand servers, which will accept it via >one NIC and do Direct Response via client/public facing NIC?

only subset of NICs supports this (redirect from one port to another). also it actually could be less effective, as it would require PCI-E bus traversal and you will start to have one more place which could be bottlenecked 

> How bonded NICs should be treated as, for e.g. is it working in driver mode?
the recomended way it to install XDP's root program to each of the physical interface inside bond (e.g. if bond contains eth0 and eth1 you would need to install it on eth0 and eth1) (example of xdp root starting: https://github.com/facebookincubator/katran/blob/master/install_xdproot.sh ; probably  you wold want to change this flag to point to something like bond0 instead of physical interface name "-bpfpath=/sys/fs/bpf/jmp_bond0" ) and than start katran in "shared" mode ( e.g. with flag "-map_path=/sys/fs/bpf/jmp_bond0"


> What Linux kernel is suggested to run with, knowing that BPF and XDP loves newer kernels.
as for official supported i'm interested as well (https://github.com/facebookincubator/katran/issues/100). as for general suggestions - the latest one you are comfortable with (well which should be above 4.15)

**Comment by udippant** [comment]
Yeah, I think it'll be useful for users if we revise the tutorial with info about new features such as GUE encapsulation, NUMA etc. I'll try to add that sometime soon (and keep this issue open to track that).

**Comment by linecolumn** [comment]
Any news on revisiting tutorial to include info about all features?

**Comment by rohith1001** [comment]
@udippant is there any mail group where we can ask our doubts?
GUE Decapsulation -- in which case this is used. I was under the assumption that Katran only supports DSR mode.
