### ISSUE TITLE
Benchmarking katran 

### ISSUE THREAD

**Issue by 7anya** [facebookincubator/katran#217]
Hi, 

I saw from this https://github.com/facebookincubator/katran/issues/170 issue that we don't have proper open-source benchmarking for katran, and maybe we could use perf_testing in katran tester. 

However, I went through the code, and it's suspiciously fast to run perf testing through katran tester compared to running katran from the GRPC example. 

Could you please explain if perf testing is just a mostly functional test or if it is limited compared to running the GRPC example? 

I collected some runtime data of XDP program while running GRPC example, using sudo bpftool p s, and it's considerably higher than the few nanoseconds we see when running perf testing. 

Also is perf testing reliable or should it not be used as a real-world benchmarking tool?

this query is time sensitive and a response ASAP will be appreciated. Thank you!

**Comment by tehnerd** [comment]
perf_tester is perf testing bpf code itself. in real world majority of  time is spent e.g. in memory management and other routines of the network card + hw memory access. you can think about perf_tester as of "upper limit for your single core"

**Comment by 7anya** [comment]
@tehnerd do you mean lower bound and not upper bound?

Also, I measured the runtime of the bpf program and not the whole katran end-to-end and the results were off. 

We did a deep dive into your perf testing code and found severe caching issues. 

1. We changed the number of trials to 1 from 1 Million, and the number of runtimes increased by 100s.
 We found that until 10000 trials the runtime plateaus and then jumps again after.

2. We suspected this was due to caching as the same packet is used in all trials and therefore decided to calculate the cache hit rate to be sure. We used perf and calculated the hit rate, which was 99.14% for L1 cache and 91% for L2 cache. 

This is probably a bug that should be fixed soon and probably mentioned in the readme somewhere. 

Thanks a lot for the response.

**Comment by tehnerd** [comment]
well yes. as i mentioned it is perf testing of upper limit of bpf code itself. because it is running same code over same memory over and over again. so both instruction and data caches are supper hot. if you want to test real world perf of bpf code itself in real environment (and again bpf code and bpf code only but with real memory access patterns; this timing wont include NICs or kernels functions) you would need to set syscatl
kernel.bpf_stats_enabled to 1

and than in bpftool prog list you would see a name of the program
number of how much this program was run and total time in ns

so avg runtime for a single packet would be that total_time / # of runs

if you are not intall balancer to interface directly but using some kind of root xdp program (as in this repo example) - you would see time reported by that root program
