### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by jlijian3** [facebookincubator/katran#23]
What's the throughput(pps)?Could you show me the data chart?

**Comment by tehnerd** [comment]
This is depends on environment and your NIC model. It’s highly advices to test on your own hardware to see the real numbers. Otherwise some numbers (and comparison to ipvs) could be found in “The eXpress Data Path: Fast Programmable Packet Processing in the Operating System Kernel” paper section 5.3 (you can google this paper. It is in public and could be easily found)

**Comment by jlijian3** [comment]
Thank you. I found it.
