### ISSUE TITLE
Question about lru

### ISSUE THREAD

**Issue by dongbin18** [facebookincubator/katran#80]
In bpf files, lru seems the cache of get_packet_dst result. How can lru handle packets when dst real server already down, but old dst still in lru map? New connection with same 5-tuple will still find the old lru dst.
Other question, why lru only handle udp timeout in connection_table_lookup, how about tcp connections?

**Comment by udippant** [comment]
> How can lru handle packets when dst real server already down, but old dst still in lru map?

If the dst real server is already down, packets for *existing connections* are sent to the same dst real server. For new connection, katran computes hash and picks a 'healthy' real server. I.e. it doesn't lookup LRU cache for new connections.

For UDP, since it is generally difficult to disambiguate 'new' connection (with the same 5-tuple like you mentioned), we have LRU cache with timeouts. For TCP, there is no such timeout for entries in the connection table since we can use TCP-SYN packets for 'new' connections.

**Comment by dongbin18** [comment]
Thanks and another question, how can lru handle persistent connection? If a persistent connection sends the keep-alive packet every hour, but there are too many new connections update lru map. Will the persistent connection be deleted in lru map?

**Comment by udippant** [comment]
Short answer is yes, existing entry can be evicted and replaced by new entries.
In that case, Katran will re-compute the hash on the 5-tuple. So if your backend servers haven't changed in the meantime, it'll pick the same one. However, if the server-ring has changed, it is possible that the packet will then be routed to a different _real_.

**Comment by dongbin18** [comment]
thanks
