### ISSUE TITLE
Can Katran handle the packets from client when its size equaled to MTU?

### ISSUE THREAD

**Issue by lzfmars** [facebookincubator/katran#82]
From my test, if the packet from client has no room for adding ipip header, Katran can't handle it. Is it right? I didn't see any codes in xdp-balancer to handle this situation. Can it be fixed?

**Comment by tehnerd** [comment]
It won’t do packet fragmentation by design. Recommended way to solve it is either to increase mtu on “Katran-> l7 proxy path” or reconfigure “advertised mss on l7” (so users wont send packets,say, bigger than 1480 bytes (v4 as example). Another way is to build Katran with -DICMP_TOOBIG_GENERATION. In this case Katran will send packets back to users if they are bigger than predefined value (which could account for additional encapsulation overhead). But this option would require something like 4.17+ kernel

**Comment by udippant** [comment]
Feel free to reopen if you have more questions.
